apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: icr.io/automation-saas-platform/tekton-baseimage:v0.1.7
  - name: icr.io/automation-saas-platform-dev/gori-experience-apps/mspui:main-1787365235
  - name: icr.io/automation-saas-platform-dev/gori-experience-apps/accountui:main-1787365235
  - name: icr.io/automation-saas-platform-dev/gori-experience-apps/xpm:main-1787365235
  - name: icr.io/automation-saas-platform-dev/acm-cuga-system:0.3.0
  - name: icr.io/automation-saas-platform-dev/main:0.3.0
  - name: icr.io/automation-saas-platform-dev/sovereign-core-upgrade-pipelines:0.3.0
  - name: icr.io/automation-saas-platform-dev/aiiaas:0.3.0
