#!/bin/bash

# Quay Team Setup Script
# This script creates teams in Quay organizations, adds a user to the teams,
# grants read permissions to all repositories, and generates a Kubernetes pull secret.

set -e

# Default values
DRY_RUN=false
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${SCRIPT_DIR}/generated"
MAX_RETRIES=3
RETRY_DELAY=2
QUAY_NAMESPACE="${QUAY_NAMESPACE:-quay-enterprise}"
AUTO_GENERATED_TOKEN=false
REVOKE_TOKEN=true
OAUTH_TOKEN_UUID=""
TEMP_ORG_ADMIN_GRANTED=false
TEMP_ORG_ADMIN_ORG="default-org"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "This script creates 'sovereign-core-read' teams in all Quay organizations,"
    echo "adds a user to the teams, grants read permissions to all repositories,"
    echo "and generates a Kubernetes pull secret."
    echo ""
    echo "Options:"
        echo "  -d, --dry-run             Validate configuration without making changes"
        echo "  -D, --debug               Enable debug logging"
        echo "  --no-revoke-token         Do not revoke auto-generated OAuth token on exit"
        echo "                            Token will be saved to .env file for reuse"
        echo "  -o, --output-dir DIR      Output directory for generated files (default: ${OUTPUT_DIR})"
    echo "  -h, --help                Show this help message"
    echo ""
    echo "Required Environment Variables:"
    echo "  QUAY_URL                  Quay registry URL (e.g., https://quay.example.com)"
    echo "  TEAM_USER_NAME            Username to add to teams"
    echo ""
    echo "Note: User password is automatically generated by Quay API"
    echo ""
    echo "Authentication (choose one):"
    echo "  Option 1: Use existing API token"
    echo "    QUAY_API_TOKEN          Admin API token for authentication"
    echo ""
    echo "  Option 2: Auto-generate OAuth token (requires Hub Cluster access)"
    echo "    QUAY_SUPER_USER         Superuser username"
    echo "    QUAY_SUPER_PASSWORD     Superuser password"
    echo "    QUAY_NAMESPACE          Hub Cluster namespace (default: quay-enterprise)"
    echo ""
    echo "Optional Environment Variables:"
    echo "  DEBUG                     Enable debug logging (true/false, default: false)"
    echo "  CURL_OPTS                 Additional curl options (e.g., '--insecure --connect-timeout 30')"
    echo ""
    echo "Examples:"
    echo "  # Set environment variables"
    echo "  export QUAY_URL=https://quay.example.com"
    echo "  export QUAY_API_TOKEN=your-admin-token"
    echo "  export TEAM_USER_NAME=readonly-user"
    echo "  export TEAM_USER_PASSWORD=user-password"
    echo ""
    echo "  # Run the script"
    echo "  $0"
    echo ""
    echo "  # Dry run to validate"
    echo "  $0 --dry-run"
    echo ""
    echo "Prerequisites:"
    echo "  - curl: HTTP client"
    echo "  - jq: JSON processor"
    echo "  - base64: Base64 encoder"
    echo ""
    exit 1
}

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1" >&2
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

log_debug() {
    if [ "${DEBUG}" = true ]; then
        echo -e "${BLUE}[DEBUG]${NC} $1" >&2
    fi
}

# Function to save OAuth token to .env file
save_token_to_env() {
    local token="$1"
    local env_file="${SCRIPT_DIR}/.env"
    
    log_debug "Attempting to save token to .env file..."
    
    # Create .env from template if it doesn't exist
    if [ ! -f "$env_file" ]; then
        log_debug ".env file not found, creating from template..."
        if [ -f "${SCRIPT_DIR}/.env.example" ]; then
            cp "${SCRIPT_DIR}/.env.example" "$env_file"
            log_debug ".env file created from template"
        else
            log_error ".env.example not found, cannot create .env file"
            return 1
        fi
    fi
    
    # Update or add QUAY_API_TOKEN
    if grep -q "^export QUAY_API_TOKEN=" "$env_file"; then
        # Update existing uncommented line
        log_debug "Updating existing QUAY_API_TOKEN line..."
        sed -i.bak "s|^export QUAY_API_TOKEN=.*|export QUAY_API_TOKEN=${token}|" "$env_file"
    elif grep -q "^# export QUAY_API_TOKEN=" "$env_file"; then
        # Uncomment and update
        log_debug "Uncommenting and updating QUAY_API_TOKEN line..."
        sed -i.bak "s|^# export QUAY_API_TOKEN=.*|export QUAY_API_TOKEN=${token}|" "$env_file"
    else
        # Add new line after QUAY_URL
        log_debug "Adding new QUAY_API_TOKEN line..."
        if grep -q "^export QUAY_URL=" "$env_file"; then
            sed -i.bak "/^export QUAY_URL=/a\\
export QUAY_API_TOKEN=${token}" "$env_file"
        else
            # If QUAY_URL not found, append to end of file
            echo "export QUAY_API_TOKEN=${token}" >> "$env_file"
        fi
    fi
    
    # Remove backup file
    rm -f "${env_file}.bak"
    
    # Verify the token was saved
    if grep -q "^export QUAY_API_TOKEN=${token}" "$env_file"; then
        log_debug "Token successfully saved to .env file"
        return 0
    else
        log_error "Failed to verify token in .env file"
        return 1
    fi
}

# Function to revoke OAuth token
# Function to get OAuth token UUID by matching scope
get_token_uuid() {
    local token="$1"
    local expected_scope="$2"
    
    if [ -z "$token" ]; then
        log_error "No token provided for UUID retrieval"
        return 1
    fi
    
    if [ -z "$expected_scope" ]; then
        log_error "No scope provided for UUID matching"
        return 1
    fi
    
    log_debug "Retrieving OAuth token UUID..."
    log_debug "  Expected scope: ${expected_scope}"
    
    # Get list of user authorizations
    local response
    local http_code
    
    response=$(curl -s -w "\n%{http_code}" $CURL_OPTS -X GET \
        -H "Authorization: Bearer ${token}" \
        "${QUAY_URL}/api/v1/user/authorizations" 2>&1)
    
    http_code=$(echo "$response" | tail -n1)
    response=$(echo "$response" | sed '$d')
    
    if [ "$http_code" -ne 200 ]; then
        log_error "Failed to retrieve user authorizations (HTTP $http_code)"
        log_debug "Response: $response"
        return 1
    fi
    
    # Parse JSON response and find matching token UUID
    # Find the last token with matching scope (most recent)
    # Sort scopes before comparison to handle different ordering
    local uuid
    log_debug "Sorting and comparing scopes (order-independent matching)..."
    uuid=$(echo "$response" | jq -r --arg scope "$expected_scope" '
        ($scope | split(" ") | sort | join(" ")) as $sorted_expected |
        .authorizations
        | map(select(.scopes | map(.scope) | sort | join(" ") == $sorted_expected))
        | last
        | .uuid // empty
    ')
    
    if [ -z "$uuid" ]; then
        log_warn "No OAuth token found with matching scope: ${expected_scope}"
        log_debug "Expected scope (sorted): $(echo "$expected_scope" | tr ' ' '\n' | sort | tr '\n' ' ')"
        log_debug "Available tokens:"
        echo "$response" | jq -r '.authorizations[] | "  UUID: \(.uuid), Scopes: \(.scopes | map(.scope) | join(" "))"' >&2
        return 1
    fi
    
    log_debug "✓ Found matching OAuth token UUID: ${uuid}"
    echo "$uuid"
    return 0
}

revoke_oauth_token() {
    local token="$1"
    local uuid="$2"
    
    if [ -z "$token" ]; then
        log_error "No token provided for revocation"
        return 1
    fi
    
    if [ -z "$uuid" ]; then
        log_error "No UUID provided for revocation"
        log_error "Cannot revoke token without UUID"
        return 1
    fi
    
    log_debug "Attempting to revoke OAuth token..."
    log_debug "  UUID: ${uuid}"
    
    # Make revoke request using DELETE API
    local response
    local http_code
    
    response=$(curl -s -w "\n%{http_code}" $CURL_OPTS -X DELETE \
        -H "Authorization: Bearer ${token}" \
        "${QUAY_URL}/api/v1/user/authorizations/${uuid}" 2>&1)
    
    http_code=$(echo "$response" | tail -n1)
    response=$(echo "$response" | sed '$d')
    
    if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
        log_info "✓ OAuth token revoked successfully"
        return 0
    else
        log_warn "Failed to revoke OAuth token (HTTP $http_code)"
        log_debug "Response: $response"
        return 1
    fi
}

# Cleanup function to revoke auto-generated token on exit
# Function to generate Kubernetes pull secret
generate_pull_secret() {
    local oauth_token="$1"
    local team_user="$2"
    local quay_url="$3"
    local output_dir="$4"
    local namespace="${5:-acm-service-broker}"
    
    log_debug ""
    log_debug "Generating Kubernetes pull secret..."
    
    mkdir -p "$output_dir"
    
    # Remove https:// prefix from QUAY_URL for docker config
    local registry_url="${quay_url#https://}"
    
    # OAuth token uses $oauthtoken as username
    local docker_username='$oauthtoken'
    
    # Create docker config JSON
    local docker_config=$(cat <<EOF
{
  "auths": {
    "${registry_url}": {
      "auth": "$(echo -n "${docker_username}:${oauth_token}" | base64)",
      "username": "${docker_username}",
      "password": "${oauth_token}"
    }
  }
}
EOF
)
    
    # Base64 encode the docker config
    local docker_config_base64=$(echo -n "$docker_config" | base64)
    
    # Generate Kubernetes Secret YAML
    local output_file="${output_dir}/pull-secret-${team_user}.yaml"
    
    cat > "$output_file" <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: quay-pull-secret-${team_user}
  namespace: ${namespace}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${docker_config_base64}
EOF
    
    log_debug "✓ Kubernetes pull secret generated: $output_file"
    echo "$output_file"
}

cleanup() {
    local exit_code=$?
    
    if [ "$TEMP_ORG_ADMIN_GRANTED" = true ]; then
        if [ "$DRY_RUN" = true ]; then
            log_info "Dry run: Would revert temporary organization admin role on ${TEMP_ORG_ADMIN_ORG}/${TEAM_NAME}"
        else
            log_info "Reverting temporary organization admin role on ${TEMP_ORG_ADMIN_ORG}/${TEAM_NAME}..."
            local revert_team_data="{\"name\":\"${TEAM_NAME}\",\"role\":\"member\",\"description\":\"${TEAM_DESCRIPTION}\"}"
            if api_call "PUT" "/api/v1/organization/${TEMP_ORG_ADMIN_ORG}/team/${TEAM_NAME}" "$revert_team_data" > /dev/null; then
                log_info "✓ Reverted temporary organization admin role on ${TEMP_ORG_ADMIN_ORG}/${TEAM_NAME}"
                TEMP_ORG_ADMIN_GRANTED=false
            else
                log_warn "Failed to revert temporary organization admin role on ${TEMP_ORG_ADMIN_ORG}/${TEAM_NAME}"
                log_warn "Please update the team role manually if needed."
            fi
        fi
    fi
    
    # Only process if token was auto-generated
    if [ "$AUTO_GENERATED_TOKEN" = true ]; then
        if [ "$REVOKE_TOKEN" = false ]; then
            # Save token to .env file for reuse
            if [ "$DRY_RUN" = true ]; then
                log_info "Dry run: Would save OAuth token to .env file"
                log_info "  Token would be saved as: QUAY_API_TOKEN=<generated-token>"
                log_info "  Next run would use this token automatically"
            else
                log_info "Saving OAuth token to .env file for reuse..."
                if save_token_to_env "$QUAY_API_TOKEN"; then
                    log_info "✓ OAuth token saved to ${SCRIPT_DIR}/.env"
                    log_info "  Next time, the script will use this token automatically"
                    log_info "  To use the saved token, run: source .env && ./create-read-only-account.sh"
                    log_warn "  Note: OAuth tokens may expire. If authentication fails, regenerate the token."
                else
                    log_warn "Failed to save OAuth token to .env file"
                    log_warn "You may need to regenerate the token on next run"
                fi
            fi
        else
            # Revoke token as before
            if [ "$DRY_RUN" = true ]; then
                log_info "Dry run: Would revoke auto-generated OAuth token"
            else
                log_info "Revoking auto-generated OAuth token..."
                if [ -n "$OAUTH_TOKEN_UUID" ]; then
                    if ! revoke_oauth_token "$QUAY_API_TOKEN" "$OAUTH_TOKEN_UUID"; then
                        log_warn "Failed to revoke OAuth token. Please revoke it manually if needed."
                    fi
                else
                    log_warn "No token UUID available. Cannot revoke token automatically."
                    log_warn "Please revoke the token manually from Quay UI if needed."
                fi
            fi
        fi
    fi
    
    exit $exit_code
}

# Register cleanup function to run on exit
trap cleanup EXIT

# Function to get OAuth credentials from Hub Cluster
get_oauth_credentials_from_hub() {
    log_info "Fetching OAuth credentials from Hub Cluster..."
    
    # Check if oc command is available
    if ! command -v oc &> /dev/null; then
        log_error "'oc' command not found. Please install OpenShift CLI."
        return 1
    fi
    
    # Check if logged in to OpenShift
    if ! oc whoami &> /dev/null; then
        log_error "Not logged in to OpenShift Cluster. Please run 'oc login'."
        return 1
    fi
    
    # Extract OAuth credentials from secret
    local secret_output
    if ! secret_output=$(oc extract -n "${QUAY_NAMESPACE}" secret/quay-oauth-credentials --to=- 2>&1); then
        log_error "Failed to get OAuth credentials"
        log_error "Namespace: ${QUAY_NAMESPACE}"
        log_error "Secret: quay-oauth-credentials"
        log_debug "Error: $secret_output"
        return 1
    fi
    
    # Parse client-id
    OAUTH_CLIENT_ID=$(echo "$secret_output" | awk '/^# client-id$/{getline; print}')
    if [ -z "$OAUTH_CLIENT_ID" ]; then
        log_error "Failed to extract Client ID"
        return 1
    fi
    
    # Parse redirect-uri
    OAUTH_REDIRECT_URI=$(echo "$secret_output" | awk '/^# redirect-uri$/{getline; print}')
    if [ -z "$OAUTH_REDIRECT_URI" ]; then
        log_error "Failed to extract Redirect URI"
        return 1
    fi
    
    log_info "✓ OAuth credentials retrieved successfully"
    log_debug "  Client ID: ${OAUTH_CLIENT_ID}"
    log_debug "  Redirect URI: ${OAUTH_REDIRECT_URI}"
    
    return 0
}

# Function to generate OAuth token
generate_oauth_token() {
    local username="$1"
    local password="$2"
    local scopes="$3"
    local client_id="$4"
    local redirect_uri="$5"
    
    log_debug "Generating OAuth token..."
    log_debug "  Username: ${username}"
    log_debug "  Scopes: ${scopes}"
    
    # Create Basic Auth header
    local auth_header=$(echo -n "${username}:${password}" | base64)
    
    # Prepare request data
    local request_data="response_type=token&client_id=${client_id}&scope=${scopes}&redirect_uri=${redirect_uri}"
    
    # Make OAuth request and capture full response including headers
    local response
    response=$(curl -s -v -X POST $CURL_OPTS \
        -d "$request_data" \
        -H "Authorization: Basic ${auth_header}" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        "${QUAY_URL}/oauth/authorizeapp" 2>&1)
    
    # Extract access token from Location header
    local token=$(echo "$response" | grep -i "^< location:" | sed -n 's/.*access_token=\([^&]*\).*/\1/p' | tr -d '\r\n')
    
    if [ -z "$token" ]; then
        log_error "Failed to generate OAuth token"
        log_debug "Response: $response"
        
        # Check for common errors
        if echo "$response" | grep -q "401"; then
            log_error "Authentication failed. Please check username and password."
        elif echo "$response" | grep -q "400"; then
            log_error "Invalid request. Please verify Client ID is whitelisted."
        fi
        
        return 1
    fi
    
    log_debug "✓ OAuth token generated successfully"
    
    echo "$token"
    return 0
}

# Parse arguments
# Support DEBUG environment variable (can be overridden by command line flag)
DEBUG="${DEBUG:-false}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        -d|--dry-run)
            DRY_RUN=true
            shift 1
            ;;
        -D|--debug)
            DEBUG=true
            shift 1
            ;;
        --no-revoke-token)
            REVOKE_TOKEN=false
            shift 1
            ;;
        -o|--output-dir)
            if [ -z "$2" ] || [[ "$2" == -* ]]; then
                log_error "Option $1 requires a value"
                usage
            fi
            OUTPUT_DIR="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            ;;
    esac
done

# Check prerequisites
log_info "Checking prerequisites..."

if ! command -v curl &> /dev/null; then
    log_error "'curl' command not found. Please install curl."
    exit 1
fi

if ! command -v jq &> /dev/null; then
    log_error "'jq' command not found. Please install jq: https://stedolan.github.io/jq/"
    exit 1
fi

if ! command -v base64 &> /dev/null; then
    log_error "'base64' command not found."
    exit 1
fi

log_info "✓ All prerequisites satisfied"

# Validate required environment variables
log_info "Validating environment variables..."

if [ -z "$QUAY_URL" ]; then
    log_error "QUAY_URL environment variable is required"
    exit 1
fi

if [ -z "$TEAM_USER_NAME" ]; then
    log_error "TEAM_USER_NAME environment variable is required"
    exit 1
fi

# Validate authentication
log_info "Validating authentication..."

if [ -z "$QUAY_API_TOKEN" ]; then
    log_info "QUAY_API_TOKEN not set. Attempting OAuth token auto-generation."
    
    # Check if superuser credentials are provided
    if [ -z "$QUAY_SUPER_USER" ] || [ -z "$QUAY_SUPER_PASSWORD" ]; then
        log_error "Authentication credentials missing. Please set one of the following:"
        log_error "  Option 1: QUAY_API_TOKEN"
        log_error "  Option 2: QUAY_SUPER_USER and QUAY_SUPER_PASSWORD"
        exit 1
    fi
    
    log_info "Superuser credentials provided. Generating OAuth token automatically."
    
    # Get OAuth credentials from Hub Cluster
    if ! get_oauth_credentials_from_hub; then
        log_error "Failed to get OAuth credentials from Hub Cluster"
        exit 1
    fi
    
    # Generate OAuth token for superuser
    log_info "Generating OAuth token for superuser..."
    SUPERUSER_SCOPES="super:user org:admin repo:admin repo:create user:admin user:read"
    
    if ! QUAY_API_TOKEN=$(generate_oauth_token "$QUAY_SUPER_USER" "$QUAY_SUPER_PASSWORD" "$SUPERUSER_SCOPES" "$OAUTH_CLIENT_ID" "$OAUTH_REDIRECT_URI"); then
        log_error "Failed to generate OAuth token for superuser"
        exit 1
    fi
    
    # Get UUID in parent shell (not in subshell) to ensure it's available for cleanup
    log_debug "Retrieving token UUID for revocation in parent shell..."
    if OAUTH_TOKEN_UUID=$(get_token_uuid "$QUAY_API_TOKEN" "$SUPERUSER_SCOPES"); then
        log_debug "✓ Token UUID retrieved in parent shell: ${OAUTH_TOKEN_UUID}"
    else
        log_warn "Failed to retrieve token UUID. Token revocation may not work properly."
        OAUTH_TOKEN_UUID=""
    fi
    
    # Mark token as auto-generated for cleanup
    AUTO_GENERATED_TOKEN=true
    
    log_info "✓ OAuth token generated successfully (auto-generated)"
    log_info "✓ Using generated token as QUAY_API_TOKEN"
    
    if [ "$REVOKE_TOKEN" = true ]; then
        log_info "Note: Token will be automatically revoked on script exit"
    else
        log_info "Note: Token will NOT be revoked on script exit (--no-revoke-token specified)"
    fi
else
    log_info "✓ Using existing API Token"
fi

# Remove trailing slash from QUAY_URL
QUAY_URL="${QUAY_URL%/}"

log_info "✓ Environment variables validated"
log_info "Quay URL: $QUAY_URL"
log_info "Team User: $TEAM_USER_NAME"
log_info "Note: User password will be automatically generated by Quay"

# Function to make API calls with retry logic
api_call() {
    local method="$1"
    local endpoint="$2"
    local data="$3"
    local retry_count=0
    local response
    local http_code
    local error_message
    
    # Set authentication header
    local auth_header="Authorization: Bearer $QUAY_API_TOKEN"
    
    while [ $retry_count -lt $MAX_RETRIES ]; do
        if [ -n "$data" ]; then
            response=$(curl -s -w "\n%{http_code}" $CURL_OPTS -X "$method" \
                -H "$auth_header" \
                -H "Content-Type: application/json" \
                -d "$data" \
                "${QUAY_URL}${endpoint}")
        else
            response=$(curl -s -w "\n%{http_code}" $CURL_OPTS -X "$method" \
                -H "$auth_header" \
                "${QUAY_URL}${endpoint}")
        fi
        
        http_code=$(echo "$response" | tail -n1)
        response=$(echo "$response" | sed '$d')
        
        # Extract error message from JSON response if available
        error_message=$(echo "$response" | jq -r '.error_message // .message // .detail // .error // empty' 2>/dev/null)
        
        if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
            echo "$response"
            return 0
        elif [ "$http_code" -eq 400 ]; then
            log_error "Bad Request (HTTP 400): Invalid request parameters"
            if [ -n "$error_message" ]; then
                log_error "API Error: $error_message"
            else
                log_error "Response: $response"
            fi
            return 1
        elif [ "$http_code" -eq 401 ]; then
            log_error "Authentication failed (HTTP 401). Please check your QUAY_API_TOKEN."
            if [ -n "$error_message" ]; then
                log_error "API Error: $error_message"
            fi
            return 1
        elif [ "$http_code" -eq 403 ]; then
            log_error "Permission denied (HTTP 403). Please ensure your credentials have admin privileges."
            if [ -n "$error_message" ]; then
                log_error "API Error: $error_message"
            fi
            return 1
        elif [ "$http_code" -eq 404 ]; then
            log_error "Resource not found (HTTP 404)"
            if [ -n "$error_message" ]; then
                log_error "API Error: $error_message"
            else
                log_error "Endpoint: $endpoint"
            fi
            return 1
        elif [ "$http_code" -eq 409 ]; then
            log_error "Conflict (HTTP 409): Resource already exists or conflict detected"
            if [ -n "$error_message" ]; then
                log_error "API Error: $error_message"
            else
                log_error "Response: $response"
            fi
            return 1
        elif [ "$http_code" -eq 422 ]; then
            log_error "Unprocessable Entity (HTTP 422): Validation failed"
            if [ -n "$error_message" ]; then
                log_error "API Error: $error_message"
            else
                log_error "Response: $response"
            fi
            return 1
        elif [ "$http_code" -ge 500 ]; then
            retry_count=$((retry_count + 1))
            if [ $retry_count -lt $MAX_RETRIES ]; then
                log_warn "Server error (HTTP $http_code). Retrying in ${RETRY_DELAY}s... (Attempt $((retry_count + 1))/$MAX_RETRIES)"
                if [ -n "$error_message" ]; then
                    log_debug "API Error: $error_message"
                fi
                sleep $RETRY_DELAY
            else
                log_error "Server error (HTTP $http_code) after $MAX_RETRIES attempts."
                if [ -n "$error_message" ]; then
                    log_error "API Error: $error_message"
                else
                    log_error "Response: $response"
                fi
                return 1
            fi
        else
            log_error "API call failed with HTTP $http_code"
            if [ -n "$error_message" ]; then
                log_error "API Error: $error_message"
            else
                log_error "Response: $response"
            fi
            return 1
        fi
    done
    
    return 1
}

# Test API connectivity
log_info "Testing API connectivity..."
if ! api_call "GET" "/api/v1/user/" > /dev/null; then
    log_error "Failed to connect to Quay API. Please check QUAY_URL and your credentials."
    exit 1
fi
log_info "✓ API connectivity verified"

# Check if team user exists, create if not
log_info "Checking if team user exists..."
AUTH_FILE="${OUTPUT_DIR}/auth-${TEAM_USER_NAME}.json"

if user_check=$(api_call "GET" "/api/v1/users/${TEAM_USER_NAME}"); then
    if echo "$user_check" | jq -e '.username' > /dev/null 2>&1; then
        log_info "✓ Team user already exists: $TEAM_USER_NAME"
        
        # Check if password is provided via environment variable
        if [ -n "$TEAM_USER_PASSWORD" ]; then
            log_info "Using password from TEAM_USER_PASSWORD environment variable"
        else
            # Try to load password from saved auth file
            if [ -f "$AUTH_FILE" ]; then
                log_info "Loading credentials from saved file: $AUTH_FILE"
                TEAM_USER_PASSWORD=$(jq -r '.password' "$AUTH_FILE")
                
                if [ -z "$TEAM_USER_PASSWORD" ] || [ "$TEAM_USER_PASSWORD" = "null" ]; then
                    log_error "Failed to load password from $AUTH_FILE"
                    log_error "Please provide TEAM_USER_PASSWORD environment variable or delete the user and re-run"
                    exit 1
                fi
                
                log_info "✓ Credentials loaded successfully"
            else
                log_error "User exists but credentials file not found: $AUTH_FILE"
                log_error "Please provide TEAM_USER_PASSWORD environment variable"
                exit 1
            fi
        fi
    else
        log_error "Invalid response when checking user existence"
        log_error "Response: $user_check"
        exit 1
    fi
else
    log_info "Team user does not exist. Creating user: $TEAM_USER_NAME"
    
    # Exit if dry run before creating user
    if [ "$DRY_RUN" = true ]; then
        log_info "Dry run: Would create user $TEAM_USER_NAME"
        log_info "Dry run: Password would be automatically generated by Quay"
        log_info "Dry run completed. Configuration is valid."
        exit 0
    fi
    
    # Create user using superuser API
    user_data=$(cat <<EOF
{
  "username": "${TEAM_USER_NAME}"
}
EOF
)
    
    if ! user_response=$(api_call "POST" "/api/v1/superuser/users/" "$user_data"); then
        log_error "Failed to create team user: $TEAM_USER_NAME"
        log_error "Please check if:"
        log_error "  - The username is not already taken"
        log_error "  - Your credentials have superuser permissions (super:user scope required)"
        log_error "  - The Quay API endpoint is accessible"
        exit 1
    fi
    
    # Validate response and extract password
    if ! echo "$user_response" | jq -e '.username' > /dev/null 2>&1; then
        log_error "User creation returned success but response is invalid"
        log_error "Response: $user_response"
        exit 1
    fi
    
    # Save user creation response to JSON file
    echo "$user_response" | jq '.' > "$AUTH_FILE"
    log_info "✓ User credentials saved: $AUTH_FILE"
    
    # Extract the auto-generated password from response
    TEAM_USER_PASSWORD=$(echo "$user_response" | jq -r '.password')
    if [ -z "$TEAM_USER_PASSWORD" ] || [ "$TEAM_USER_PASSWORD" = "null" ]; then
        log_error "Failed to extract password from user creation response"
        log_error "Response: $user_response"
        exit 1
    fi
    
    log_info "✓ Team user created successfully: $TEAM_USER_NAME"
    log_info "✓ Password automatically generated by Quay"
fi


# Exit if dry run
if [ "$DRY_RUN" = true ]; then
    log_info "Dry run completed. Configuration is valid."
    exit 0
fi

# Get all organizations
log_info "Fetching organizations..."
if ! orgs_response=$(api_call "GET" "/api/v1/user/"); then
    log_error "Failed to fetch organizations"
    exit 1
fi

# Validate response
if ! echo "$orgs_response" | jq -e '.organizations' > /dev/null 2>&1; then
    log_error "Invalid response when fetching organizations"
    log_error "Response: $orgs_response"
    exit 1
fi

# Extract organization names
orgs=$(echo "$orgs_response" | jq -r '.organizations[]?.name // empty')

# Ensure aiiaas-models organization exists
TARGET_ORG="aiiaas-models"
if echo "$orgs" | grep -Fxq "$TARGET_ORG"; then
    log_info "✓ Organization already exists: $TARGET_ORG"
else
    log_info "Organization not found. Creating: $TARGET_ORG"
    org_data="{\"name\":\"${TARGET_ORG}\"}"
    if ! create_org_response=$(api_call "POST" "/api/v1/organization/" "$org_data"); then
        log_error "Failed to create organization: $TARGET_ORG"
        exit 1
    fi

    if [ "$create_org_response" != "\"Created\"" ] && [ "$create_org_response" != "Created" ]; then
        log_error "Invalid response when creating organization: $TARGET_ORG"
        log_error "Response: $create_org_response"
        exit 1
    fi

    if [ -n "$orgs" ]; then
        orgs="${orgs}
${TARGET_ORG}"
    else
        orgs="${TARGET_ORG}"
    fi

    log_info "✓ Organization created: $TARGET_ORG"
fi

if [ -z "$orgs" ]; then
    log_error "No organizations available to process."
    exit 1
fi

log_info "✓ Found $(echo "$orgs" | wc -l | tr -d ' ') organizations"

# Team configuration
TEAM_NAME="sovereign-core-read"
TEAM_DESCRIPTION="Read access for sovereign core images"

# Counters for summary
total_orgs=0
total_repos=0
total_success=0
total_skip=0
total_error=0

# Process each organization
while IFS= read -r org; do
    total_orgs=$((total_orgs + 1))
    log_info ""
    log_info "Processing organization: $org"
    
    # Check if team exists by getting organization info first (avoids 404 errors)
    log_info "  Checking team: $TEAM_NAME"
    user_already_in_team=false
    
    # Get organization info to check if team exists
    org_info=$(api_call "GET" "/api/v1/organization/${org}")
    
    if echo "$org_info" | jq -e ".teams.\"${TEAM_NAME}\"" > /dev/null 2>&1; then
        # Team exists - get member information
        log_info "  ✓ Team already exists"
        
        if team_check=$(api_call "GET" "/api/v1/organization/${org}/team/${TEAM_NAME}/members"); then
            # Check if user is already a member
            if echo "$team_check" | jq -e ".members[] | select(.name==\"${TEAM_USER_NAME}\")" > /dev/null 2>&1; then
                log_info "  ✓ User already in team"
                user_already_in_team=true
            fi
        else
            log_warn "  ✗ Failed to get team members in $org (continuing with other organizations)"
            continue
        fi
    else
        # Team does not exist - create it
        log_info "  Creating team: $TEAM_NAME"
        team_data="{\"name\":\"${TEAM_NAME}\",\"role\":\"member\",\"description\":\"${TEAM_DESCRIPTION}\"}"
        if ! team_response=$(api_call "PUT" "/api/v1/organization/${org}/team/${TEAM_NAME}" "$team_data"); then
            log_warn "  ✗ Failed to create team in $org (continuing with other organizations)"
            continue
        fi
        
        # Validate response
        if ! echo "$team_response" | jq -e '.name' > /dev/null 2>&1; then
            log_warn "  ✗ Team creation returned success but response is invalid for $org (continuing)"
            continue
        fi
        
        log_info "  ✓ Team created"
    fi
    
    # Add user to team (skip if already a member)
    if [ "$user_already_in_team" = true ]; then
        log_info "  Skipping user addition (already a member)"
    else
        log_info "  Adding user to team..."
        if member_response=$(api_call "PUT" "/api/v1/organization/${org}/team/${TEAM_NAME}/members/${TEAM_USER_NAME}" ""); then
            log_info "  ✓ User added to team"
        else
            log_warn "  ✗ Failed to add user to team in $org (continuing with other organizations)"
            continue
        fi
    fi
    
    # Set up default permissions for the team
    log_info "  Checking default permissions..."
    
    if [ "$DRY_RUN" = true ]; then
        log_info "  Dry run: Would check and create default permission for team ${TEAM_NAME}"
        log_info "    Role: read"
        log_info "    Delegate: team/${TEAM_NAME}"
        log_info "    Condition: Anyone (applies to all new repositories)"
    else
        # Check existing default permissions
        if default_perms=$(api_call "GET" "/api/v1/organization/${org}/prototypes"); then
            # Validate response
            if echo "$default_perms" | jq -e '.prototypes' > /dev/null 2>&1; then
                # Check if default permission already exists for this team with read role
                existing_default=$(echo "$default_perms" | jq -r ".prototypes[]? | select(.delegate.name==\"${TEAM_NAME}\" and .delegate.kind==\"team\" and .role==\"read\") | .id" 2>/dev/null)
                
                if [ -n "$existing_default" ]; then
                    log_info "  ✓ Default permission already exists for team"
                else
                    log_info "  Creating default permission for team..."
                    
                    # Create default permission with Anyone condition (activating_user is null)
                    default_perm_data=$(cat <<EOF
{
  "role": "read",
  "delegate": {
    "name": "${TEAM_NAME}",
    "kind": "team"
  }
}
EOF
)
                    
                    if default_response=$(api_call "POST" "/api/v1/organization/${org}/prototypes" "$default_perm_data"); then
                        # Validate response
                        if echo "$default_response" | jq -e '.id' > /dev/null 2>&1; then
                            log_info "  ✓ Default permission created successfully"
                            log_info "    New repositories will automatically grant read access to ${TEAM_NAME}"
                        else
                            log_warn "  ✗ Default permission creation returned success but response is invalid"
                            log_debug "    Response: $default_response"
                        fi
                    else
                        log_warn "  ✗ Failed to create default permission (continuing with existing repositories)"
                    fi
                fi
            else
                log_warn "  ✗ Invalid response when checking default permissions (continuing)"
                log_debug "    Response: $default_perms"
            fi
        else
            log_warn "  ✗ Failed to check default permissions (continuing with existing repositories)"
        fi
    fi
    
    # Fetch repositories for this organization
    log_info "  Fetching repositories for $org..."
    org_repos=()
    next_page=""
    page_num=1
    max_pages=500
    
    while [ $page_num -le $max_pages ]; do
        log_debug "    Fetching page $page_num..."
        
        # Build API URL with next_page token if available
        if [ -z "$next_page" ]; then
            api_url="/api/v1/repository?namespace=${org}&public=false"
        else
            api_url="/api/v1/repository?namespace=${org}&public=false&next_page=${next_page}"
        fi
        
        if ! repos_response=$(api_call "GET" "$api_url"); then
            log_warn "    Failed to fetch repositories for $org"
            break
        fi
        
        # Validate response
        if ! echo "$repos_response" | jq -e '.repositories' > /dev/null 2>&1; then
            log_warn "    Invalid response when fetching repositories for $org"
            break
        fi
        
        # Extract repository names
        repos=$(echo "$repos_response" | jq -r '.repositories[]? | .name')
        
        if [ -z "$repos" ]; then
            break
        fi
        
        # Add repositories to array
        while IFS= read -r repo_name; do
            org_repos+=("$repo_name")
        done <<< "$repos"
        
        # Get next page token
        next_page=$(echo "$repos_response" | jq -r '.next_page // empty')
        if [ -z "$next_page" ]; then
            log_debug "    No more pages"
            break
        fi
        
        page_num=$((page_num + 1))
    done
    
    # Warn if maximum page limit reached
    if [ $page_num -gt $max_pages ]; then
        log_warn "    Reached maximum page limit ($max_pages) for $org"
    fi
    
    repo_count=${#org_repos[@]}
    total_repos=$((total_repos + repo_count))
    log_info "  ✓ Found $repo_count repositories"
    
    if [ $repo_count -eq 0 ]; then
        log_warn "  No repositories found in $org"
        continue
    fi
    
    # Fetch existing team permissions to avoid duplicate API calls
    log_info "  Fetching existing team permissions..."
    existing_perms_list=""
    use_bulk_check=true
    
    if perms_response=$(api_call "GET" "/api/v1/organization/${org}/team/${TEAM_NAME}/permissions"); then
        # Validate response
        if echo "$perms_response" | jq -e '.permissions' > /dev/null 2>&1; then
            # Parse existing permissions into newline-separated list (repo_name:role format)
            existing_perms_list=$(echo "$perms_response" | jq -r '.permissions[]? | "\(.repository.name):\(.role)"' 2>/dev/null)
            
            if [ -n "$existing_perms_list" ]; then
                existing_count=$(echo "$existing_perms_list" | wc -l | tr -d ' ')
                log_info "  ✓ Found $existing_count existing permissions"
            else
                log_info "  ✓ No existing permissions found"
            fi
        else
            log_warn "  ✗ Invalid response when fetching team permissions, will check individually"
            use_bulk_check=false
        fi
    else
        log_warn "  ✗ Failed to fetch team permissions, will check individually"
        use_bulk_check=false
    fi
    
    # Grant team permissions to all repositories
    log_info "  Granting team permissions..."
    
    success_count=0
    skip_count=0
    error_count=0
    
    for repo_name in "${org_repos[@]}"; do
        log_debug "    Processing: ${org}/${repo_name}"
        
        # Check if permission already exists (using bulk check if available)
        if [ "$use_bulk_check" = true ] && [ -n "$existing_perms_list" ]; then
            # Search for repo_name in existing permissions list
            existing_entry=$(echo "$existing_perms_list" | grep "^${repo_name}:" || true)
            if [ -n "$existing_entry" ]; then
                existing_role=$(echo "$existing_entry" | cut -d':' -f2)
                if [ "$existing_role" = "read" ]; then
                    skip_count=$((skip_count + 1))
                    log_debug "      - Permission already exists (role: $existing_role)"
                    continue
                else
                    log_debug "      ! Existing permission has different role: $existing_role, will update to read"
                fi
            fi
        fi
        
        # Grant permission to team
        perm_data='{"role":"read"}'
        if perm_response=$(api_call "PUT" "/api/v1/repository/${org}/${repo_name}/permissions/team/${TEAM_NAME}" "$perm_data"); then
            # Validate response
            if echo "$perm_response" | jq -e '.role' > /dev/null 2>&1; then
                success_count=$((success_count + 1))
                log_debug "      ✓ Granted read permission"
            else
                # Success but no validation - count as success anyway
                success_count=$((success_count + 1))
                log_debug "      ✓ Granted read permission (no validation)"
            fi
        else
            # Fallback: Check if permission already exists (for cases where bulk check failed)
            if [ "$use_bulk_check" = false ]; then
                if existing_perm=$(api_call "GET" "/api/v1/repository/${org}/${repo_name}/permissions/team/${TEAM_NAME}"); then
                    if echo "$existing_perm" | jq -e '.role' > /dev/null 2>&1; then
                        skip_count=$((skip_count + 1))
                        log_debug "      - Permission already exists"
                    else
                        error_count=$((error_count + 1))
                        log_warn "      ✗ Failed to grant permission to ${org}/${repo_name}"
                    fi
                else
                    error_count=$((error_count + 1))
                    log_warn "      ✗ Failed to grant permission to ${org}/${repo_name}"
                fi
            else
                error_count=$((error_count + 1))
                log_warn "      ✗ Failed to grant permission to ${org}/${repo_name}"
            fi
        fi
    done
    
    total_success=$((total_success + success_count))
    total_skip=$((total_skip + skip_count))
    total_error=$((total_error + error_count))
    
    log_info "  ✓ Permission grant completed for $org"
    log_info "    Success: $success_count, Skipped: $skip_count, Errors: $error_count"
done <<< "$orgs"

log_info ""
log_info "✓ All organizations processed"
log_info "  Organizations: $total_orgs"
log_info "  Total repositories: $total_repos"
log_info "  Total success: $total_success"
log_info "  Total skipped: $total_skip"
if [ $total_error -gt 0 ]; then
    log_warn "  Total errors: $total_error"
fi

# Load or generate OAuth token for team user after team setup is complete
TEAM_USER_SCOPES="repo:read"
TEAM_USER_OAUTH_TOKEN=""

if [ -f "$AUTH_FILE" ]; then
    TEAM_USER_OAUTH_TOKEN=$(jq -r '.oauth_token // empty' "$AUTH_FILE")
    
    if [ -n "$TEAM_USER_OAUTH_TOKEN" ]; then
        log_info "✓ Using existing OAuth token from credentials file"
    fi
fi

if [ -z "$TEAM_USER_OAUTH_TOKEN" ]; then
    if [ -n "$OAUTH_CLIENT_ID" ] && [ -n "$OAUTH_REDIRECT_URI" ]; then
        log_info "OAuth token not found in credentials file. Generating OAuth token for team user..."
        
        if [ "$DRY_RUN" = true ]; then
            log_info "Dry run: Would temporarily grant organization admin role to ${TEAM_NAME} in ${TEMP_ORG_ADMIN_ORG} before token generation"
            log_info "Dry run: Would revert organization admin role to member after token generation"
            if TEAM_USER_OAUTH_TOKEN=$(generate_oauth_token "$TEAM_USER_NAME" "$TEAM_USER_PASSWORD" "$TEAM_USER_SCOPES" "$OAUTH_CLIENT_ID" "$OAUTH_REDIRECT_URI"); then
                log_info "✓ OAuth token generated for team user"
            else
                log_warn "Failed to generate OAuth token for team user (continuing without it)"
            fi
        else
            temp_admin_team_data="{\"name\":\"${TEAM_NAME}\",\"role\":\"admin\",\"description\":\"${TEAM_DESCRIPTION}\"}"
            log_info "Temporarily granting organization admin role to ${TEAM_NAME} in ${TEMP_ORG_ADMIN_ORG}..."
            if api_call "PUT" "/api/v1/organization/${TEMP_ORG_ADMIN_ORG}/team/${TEAM_NAME}" "$temp_admin_team_data" > /dev/null; then
                TEMP_ORG_ADMIN_GRANTED=true
                log_info "✓ Temporary organization admin role granted to ${TEAM_NAME} in ${TEMP_ORG_ADMIN_ORG}"
            else
                log_warn "Failed to grant temporary organization admin role to ${TEAM_NAME} in ${TEMP_ORG_ADMIN_ORG}"
                log_warn "Skipping OAuth token generation for team user"
                TEAM_USER_OAUTH_TOKEN=""
            fi
            
            if [ "$TEMP_ORG_ADMIN_GRANTED" = true ]; then
                if TEAM_USER_OAUTH_TOKEN=$(generate_oauth_token "$TEAM_USER_NAME" "$TEAM_USER_PASSWORD" "$TEAM_USER_SCOPES" "$OAUTH_CLIENT_ID" "$OAUTH_REDIRECT_URI"); then
                    log_info "✓ OAuth token generated for team user"
                else
                    log_warn "Failed to generate OAuth token for team user (continuing without it)"
                fi
                
                revert_team_data="{\"name\":\"${TEAM_NAME}\",\"role\":\"member\",\"description\":\"${TEAM_DESCRIPTION}\"}"
                log_info "Reverting temporary organization admin role on ${TEMP_ORG_ADMIN_ORG}/${TEAM_NAME}..."
                if api_call "PUT" "/api/v1/organization/${TEMP_ORG_ADMIN_ORG}/team/${TEAM_NAME}" "$revert_team_data" > /dev/null; then
                    TEMP_ORG_ADMIN_GRANTED=false
                    log_info "✓ Reverted organization admin role to member for ${TEAM_NAME} in ${TEMP_ORG_ADMIN_ORG}"
                else
                    log_warn "Failed to revert organization admin role to member for ${TEAM_NAME} in ${TEMP_ORG_ADMIN_ORG}"
                    log_warn "Cleanup will retry role reversion on script exit"
                fi
            fi
        fi
        
        if [ -n "$TEAM_USER_OAUTH_TOKEN" ]; then
            if [ -f "$AUTH_FILE" ]; then
                temp_file=$(mktemp)
                jq --arg token "$TEAM_USER_OAUTH_TOKEN" '. + {oauth_token: $token}' "$AUTH_FILE" > "$temp_file"
                mv "$temp_file" "$AUTH_FILE"
                log_info "✓ OAuth token added to credentials file: $AUTH_FILE"
            else
                log_warn "Auth file not found, OAuth token not saved to file"
            fi
        fi
    else
        log_warn "OAuth token not found in credentials file and OAuth client credentials are unavailable"
        log_warn "Skipping OAuth token generation for team user"
    fi
fi

# Generate pull secret if OAuth token is available
PULL_SECRET_FILE=""
if [ -n "$TEAM_USER_OAUTH_TOKEN" ]; then
    log_info ""
    log_info "OAuth token available, generating Kubernetes pull secret..."
    
    # Set namespace from environment or use default
    NAMESPACE="${NAMESPACE:-acm-service-broker}"
    
    if PULL_SECRET_FILE=$(generate_pull_secret "$TEAM_USER_OAUTH_TOKEN" "$TEAM_USER_NAME" "$QUAY_URL" "$OUTPUT_DIR" "$NAMESPACE"); then
        log_info "✓ Pull secret generation completed"
    else
        log_warn "Failed to generate pull secret"
        PULL_SECRET_FILE=""
    fi
fi

# Summary
echo ""
echo "=========================================="
log_info "Setup completed successfully!"
echo "=========================================="
echo ""
echo "Team Name: $TEAM_NAME"
echo "Team User: $TEAM_USER_NAME"
echo "Organizations processed: $total_orgs"
echo "Total repositories with team access: $total_repos"
echo ""
echo "Authentication file saved: $AUTH_FILE"

if [ -n "$PULL_SECRET_FILE" ]; then
    echo ""
    echo "=========================================="
    echo "KUBERNETES PULL SECRET:"
    echo "=========================================="
    echo ""
    echo "Pull secret generated: $PULL_SECRET_FILE"
    echo "Namespace: ${NAMESPACE:-acm-service-broker}"
    echo ""
    echo "To apply the secret to your cluster:"
    echo "  kubectl apply -f $PULL_SECRET_FILE"
    echo ""
else
    echo ""
    echo "=========================================="
    echo "NEXT STEPS:"
    echo "=========================================="
    echo ""
    echo "OAuth token was not generated automatically."
    echo "To create a Kubernetes pull secret, you have two options:"
    echo ""
    echo "Option 1: Use the auto-generated OAuth token (if available in auth file):"
    echo "  If the auth file contains an 'oauth_token' field, you can use it directly."
    echo ""
    echo "Option 2: Create an Application Token in Quay UI:"
    echo "   a. Log in to Quay: $QUAY_URL"
    echo "   b. Use credentials from: $AUTH_FILE"
    echo "      Username: $TEAM_USER_NAME"
    echo "      Password: (see 'password' field in the JSON file)"
    echo "   c. Go to: Account Settings → Application Tokens"
    echo "   d. Click 'Generate New Token'"
    echo "   e. Copy the generated token"
    echo ""
    echo "Then manually create the pull secret using kubectl or other tools."
fi

echo ""
echo "=========================================="

# Made with Bob