kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
    - name: icr.io/automation-saas-platform-dev/cuga-service-broker:main-<>
    - name: icr.io/automation-saas-platform-dev/cuga-operator:main-<>
    - name: icr.io/automation-saas-platform-dev/cuga:<>
    - name: cp.icr.io/cp/concert/rojacore:v2.4.0.prerelease01.patch01-7-20260428.050726-v2.4.0.prerelease01-patches

#TODO update image tages/digests
